//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPortfolio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class about
    {
        public int id_about { get; set; }
        public string about_me { get; set; }
        public string current_position { get; set; }
        public Nullable<System.DateTime> birthday { get; set; }
        public string city { get; set; }
        public string country { get; set; }
        public Nullable<int> age { get; set; }
        public string degree { get; set; }
    }
}
